"""Generate static site files and ZIP exports."""

from __future__ import annotations

import json
import uuid
import zipfile
from datetime import UTC, datetime
from pathlib import Path

from app.schemas import AssetReference, BuildManifest, DesignSpec
from app.services.providers.template_engine import make_index_filename
from app.services.storage import copy_project_assets, project_export_dir


def _render_nav(design: DesignSpec) -> str:
    links = []
    for page in design.pages:
        filename = make_index_filename(page.slug)
        label = page.title
        links.append(f'<a href="{filename}">{label}</a>')
    return "\n".join(links)


def _render_section(section_name: str, section_layout: str, page_title: str, visual_label: str) -> str:
    return f"""
    <section class="content-block">
      <div class="section-kicker">{page_title}</div>
      <h2>{section_name}</h2>
      <p>{section_layout.capitalize()} that keeps the story clean, direct, and conversion-minded.</p>
      <div class="section-grid">
        <div>
          <p>Use this block for tailored copy, proof points, and concise supporting detail.</p>
        </div>
        <div class="visual-placeholder">{visual_label}</div>
      </div>
    </section>
    """


def _render_page(design: DesignSpec, page_slug: str, copied_assets: list[str]) -> str:
    page = next(item for item in design.pages if item.slug == page_slug)
    first_asset = copied_assets[0] if copied_assets else ""
    hero_visual = (
        f'<img class="hero-image" src="{first_asset}" alt="{design.project_name} visual" />'
        if first_asset and page_slug == "index"
        else '<div class="hero-image placeholder">Add licensed or uploaded imagery here</div>'
    )
    sections_html = "\n".join(
        _render_section(section.name, section.layout, page.title, section.name)
        for section in page.sections
    )
    return f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{page.title} | {design.project_name}</title>
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <div class="background-glow glow-a"></div>
    <div class="background-glow glow-b"></div>
    <header class="site-header">
      <a class="brand" href="index.html">{design.project_name}</a>
      <nav class="site-nav">
        {_render_nav(design)}
      </nav>
    </header>
    <main>
      <section class="hero">
        <div class="hero-copy">
          <p class="eyebrow">Static export generated by Website Generator Platform</p>
          <h1>{page.hero_message}</h1>
          <p>{design.content_strategy[0]}</p>
          <div class="hero-actions">
            <a class="primary-button" href="#contact">Start a conversation</a>
            <a class="secondary-button" href="#proof">See the structure</a>
          </div>
        </div>
        <div class="hero-visual">
          {hero_visual}
        </div>
      </section>
      {sections_html}
      <section class="content-block contact-block" id="contact">
        <div class="section-kicker">Call to Action</div>
        <h2>Turn the draft into a launch-ready site</h2>
        <p>Replace this placeholder CTA with the project's real conversion action, booking link, or contact method.</p>
      </section>
    </main>
    <footer class="site-footer">
      <p>Generated for {design.project_name}. Replace placeholder copy, proof, and imagery before production launch.</p>
    </footer>
    <script src="app.js"></script>
  </body>
</html>
"""


def _render_styles(design: DesignSpec) -> str:
    colors = design.visual_direction.colors
    return f"""
:root {{
  --ink: {colors[0]};
  --surface: {colors[2]};
  --accent: {colors[3]};
  --accent-soft: {colors[4]};
  --secondary: {colors[1]};
  --border: rgba(14, 28, 54, 0.12);
  --shadow: 0 20px 50px rgba(14, 28, 54, 0.18);
  --radius: 28px;
  --max-width: 1180px;
  --font-ui: "Space Grotesk", "Avenir Next", sans-serif;
  --font-display: "Fraunces", "Georgia", serif;
}}

* {{ box-sizing: border-box; }}
html {{ scroll-behavior: smooth; }}
body {{
  margin: 0;
  font-family: var(--font-ui);
  background:
    radial-gradient(circle at top left, rgba(247, 178, 103, 0.22), transparent 30%),
    linear-gradient(180deg, #fffdf7 0%, #f4f1de 100%);
  color: var(--ink);
  min-height: 100vh;
}}

a {{ color: inherit; text-decoration: none; }}
img {{ max-width: 100%; display: block; }}
main, .site-header, .site-footer {{
  width: min(calc(100% - 32px), var(--max-width));
  margin: 0 auto;
}}

.site-header {{
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 28px 0 16px;
  position: sticky;
  top: 0;
  backdrop-filter: blur(14px);
}}

.brand {{
  font-family: var(--font-display);
  font-size: 1.35rem;
  font-weight: 700;
}}

.site-nav {{
  display: flex;
  gap: 14px;
  flex-wrap: wrap;
}}

.site-nav a {{
  padding: 10px 14px;
  border-radius: 999px;
  background: rgba(255, 255, 255, 0.74);
  border: 1px solid var(--border);
}}

.hero {{
  display: grid;
  grid-template-columns: 1.1fr 0.9fr;
  gap: 28px;
  padding: 40px 0 24px;
}}

.hero-copy, .hero-visual, .content-block {{
  background: rgba(255, 255, 255, 0.78);
  border: 1px solid var(--border);
  box-shadow: var(--shadow);
  border-radius: var(--radius);
}}

.hero-copy {{
  padding: 42px;
}}

.hero-copy h1 {{
  font-family: var(--font-display);
  font-size: clamp(2.5rem, 4vw, 4.8rem);
  line-height: 0.96;
  margin: 12px 0 16px;
}}

.hero-visual {{
  min-height: 420px;
  padding: 24px;
  display: flex;
  align-items: center;
  justify-content: center;
}}

.hero-image {{
  border-radius: 20px;
  width: 100%;
  height: 100%;
  object-fit: cover;
}}

.hero-image.placeholder, .visual-placeholder {{
  display: grid;
  place-items: center;
  min-height: 220px;
  border: 1px dashed var(--secondary);
  border-radius: 20px;
  background: linear-gradient(135deg, rgba(42,111,151,0.12), rgba(247,178,103,0.18));
}}

.hero-actions {{
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
  margin-top: 24px;
}}

.primary-button, .secondary-button {{
  padding: 14px 18px;
  border-radius: 999px;
}}

.primary-button {{
  background: var(--accent);
  color: white;
}}

.secondary-button {{
  border: 1px solid var(--border);
  background: white;
}}

.content-block {{
  padding: 32px;
  margin: 22px auto;
}}

.section-kicker, .eyebrow {{
  text-transform: uppercase;
  letter-spacing: 0.12em;
  font-size: 0.78rem;
  color: var(--secondary);
}}

.content-block h2 {{
  font-family: var(--font-display);
  font-size: clamp(2rem, 3vw, 3rem);
  margin: 10px 0 8px;
}}

.section-grid {{
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 18px;
  margin-top: 18px;
}}

.site-footer {{
  padding: 24px 0 48px;
  color: rgba(14, 28, 54, 0.8);
}}

.background-glow {{
  position: fixed;
  inset: auto;
  width: 320px;
  height: 320px;
  border-radius: 50%;
  filter: blur(60px);
  opacity: 0.5;
  pointer-events: none;
}}

.glow-a {{ top: -40px; left: -40px; background: rgba(247, 178, 103, 0.5); }}
.glow-b {{ right: -60px; bottom: 60px; background: rgba(42, 111, 151, 0.35); }}

@media (max-width: 860px) {{
  .site-header {{
    position: static;
    flex-direction: column;
    align-items: flex-start;
    gap: 12px;
  }}

  .hero,
  .section-grid {{
    grid-template-columns: 1fr;
  }}

  .hero-copy,
  .hero-visual,
  .content-block {{
    padding: 24px;
  }}
}}
"""


def _render_script() -> str:
    return """
document.querySelectorAll('.site-nav a').forEach((link) => {
  link.addEventListener('click', () => {
    document.body.classList.add('navigating');
    window.setTimeout(() => document.body.classList.remove('navigating'), 200);
  });
});
"""


def _render_export_readme(design: DesignSpec, copied_assets: list[str]) -> str:
    asset_lines = "\n".join(f"- {item}" for item in copied_assets) or "- No uploaded assets were bundled."
    return f"""# Generated Site Export

Project: {design.project_name}

## Included files

- Shared `styles.css`
- Shared `app.js`
- {len(design.pages)} HTML page(s)
- Uploaded assets copied into `assets/`
- `manifest.json`

## Before production launch

- Replace placeholder copy, proof points, and contact details
- Verify asset licenses for any external imagery you select
- Review mobile spacing and CTA destinations
- Add analytics, forms, or deployment-specific tags as needed

## Bundled assets

{asset_lines}
"""


def generate_static_export(
    project_id: str,
    design: DesignSpec,
    *,
    provider: str,
    model: str,
    asset_paths: list[str],
    image_plan: list[AssetReference],
) -> tuple[BuildManifest, str, str]:
    build_id = f"build_{uuid.uuid4().hex[:12]}"
    export_root = project_export_dir(project_id, build_id)
    copied_assets = copy_project_assets(asset_paths, export_root)

    generated_files: list[str] = []
    for page in design.pages:
        filename = make_index_filename(page.slug)
        file_path = export_root / filename
        file_path.write_text(_render_page(design, page.slug, copied_assets), encoding="utf-8")
        generated_files.append(filename)

    styles_path = export_root / "styles.css"
    styles_path.write_text(_render_styles(design), encoding="utf-8")
    generated_files.append("styles.css")

    script_path = export_root / "app.js"
    script_path.write_text(_render_script(), encoding="utf-8")
    generated_files.append("app.js")

    readme_path = export_root / "README.md"
    readme_path.write_text(_render_export_readme(design, copied_assets), encoding="utf-8")
    generated_files.append("README.md")

    manifest = BuildManifest(
        project_name=design.project_name,
        build_id=build_id,
        site_title=design.project_name,
        generated_at=datetime.now(UTC),
        provider=provider,  # type: ignore[arg-type]
        model=model,
        pages=[make_index_filename(page.slug) for page in design.pages],
        files=generated_files + copied_assets + ["manifest.json"],
        assets=image_plan,
        notes=[
            "Generated as a static brochure-style website export.",
            "Uploaded assets were bundled when present.",
            "Internet image recommendations remain metadata and are not downloaded automatically.",
        ],
    )

    manifest_path = export_root / "manifest.json"
    manifest_path.write_text(json.dumps(manifest.model_dump(mode="json"), indent=2), encoding="utf-8")

    zip_path = export_root.parent / f"{build_id}.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as bundle:
        for path in export_root.rglob("*"):
            if path.is_file():
                bundle.write(path, path.relative_to(export_root))

    return manifest, str(export_root), str(zip_path)
